#!/bin/bash
# 2016 (c) Artem Kurashov <mail@saahriktu.org> under GNU GPLv3

#control variables
PKGNAM=ha
VERSION=0.999
ARCH=$(uname -m)
BUILD=${BUILD:-1}

#building
cd ha
cmake CMakeLists.txt
make

#packaging
mkdir -p data/usr/bin
cp ha data/usr/bin
strip -s data/usr/bin/ha
chmod 755 data/usr/bin/ha
mkdir data/install
cp ../slack-desc  data/install
cd data
makepkg -c y ../../$PKGNAM-$VERSION-$ARCH-$BUILD.txz

#cleaning
cd ../..
rm -r ha
